OWWidget: Move 'splitter' to private members
'splitter' is to generic name that can be (and is) used by subclasses
that now (since gh-2743) raise an "AttributeError: 'QSplitter' object
has no attribute 'setControlAreaVisible'" in `OWWidget.showEvent`